module.exports = {
  target: "serverless",
  env: {
    GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
    NEXT_PUBLIC_EMAIL_SERVICE:process.env.NEXT_PUBLIC_EMAIL_SERVICE,
    NEXT_PUBLIC_EMAIL_TEMPLATE:process.env.NEXT_PUBLIC_EMAIL_TEMPLATE,
    NEXT_PUBLIC_EMAIL_USER:process.env.NEXT_PUBLIC_EMAIL_USER
  },
};